import DataProvider from "@/components/DataProvider";
import type { Metadata } from "next";
import BrandTopper from "@/components/BrandTopper";
import PageContent from "@/components/PageContent";
import BrandFooter from "@/components/BrandFooter";
import "./globals.scss";

export const metadata: Metadata = {
  title: "Tuition Tracker",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <DataProvider>
          <BrandTopper />
          <PageContent>
            {children}
          </PageContent>
          <BrandFooter />
        </DataProvider>
      </body>
    </html>
  );
}
